#!/bin/bash

if [ -z "$1" ]; then
	target="./a.out"
else
	target="$1"
fi


infiles=$(find data/tests/*.in* | sort -V)
outfile="data/t.out"
logfile="data/t.err"

total=$(echo "$infiles" | wc -l)
pass=0
duration=0

for infile in $infiles; do
	
	TIMEFORMAT='%U'
	# swap stdout and sterr because bash time is dumb
	# TODO: somehow combine stdout and sterr to logfile without messing with time result
	elapsed=$(time ($target < $infile > $outfile 2> $logfile; exec 3>&2 2>&1 1>&3-;) 2>> $logfile)
	duration=$(awk 'BEGIN {print ($duration+$elapsed)}')

	fname=${infile/"in"/"out"}
	res=$(diff -q -Z $fname $outfile)
	
	fname=$(basename -- "$fname")
	if [ "$res" == "" ]; then
		echo $fname: [AC $elapsed\s]
		pass=$(($pass + 1))
	else
		echo $fname: [WA $elapsed\s]
		cat $logfile
		cat $outfile
		break
	fi
done

duration=$(printf %.3f $duration)s
echo "all: [$pass/$total $duration]"
