#!/bin/bash

if [ -z "$1" ]; then
	target="./a.out"
else
	target="$1"
fi


infiles=$(find data/tests/*.in* | sort -V)
outfile="data/t.out"

total=$(echo "$infiles" | wc -l)
pass=0
duration=0

for infile in $infiles; do
	
	TIMEFORMAT='%U'
	elapsed=$(time ( $target < $infile > $outfile ) 2>&1 1>/dev/null)
	duration=$(echo "$duration + $elapsed" | bc)

	fname=${infile/"in"/"out"}
	res=$(diff -q -Z $fname $outfile)
	
	fname=$(basename -- "$fname")
	if [ "$res" == "" ]; then
		echo $fname: [AC $elapsed\s]
		pass=$(($pass + 1))
	else
		echo $fname: [WA $elapsed\s]
		# break
	fi
done

duration=$(printf %.3f $duration)s
echo "all: [$pass/$total $duration]"